# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", ip: "192.168.1.22"
  config.vm.provider "virtualbox" do |vb|
     vb.name = "ansible-node01"
     vb.cpus = 2
     vb.memory = "1500"
  end   
  config.vm.provision "file", source: "id_rsa.pub", destination: "/tmp/"
  config.vm.provision "file", source: "ansadmin"    , destination: "/tmp/" 
  config.vm.provision "file", source: "init_script.sh", destination: "/tmp/"
  config.vm.provision "shell",inline: "/bin/bash /tmp/init_script.sh"
end
